<template>
  <LandingContainer>
    <div class="terms-conditions">
      <h1 class="policy-title">
        <strong>Terms & Conditions - DigitalSeal Studio</strong>
      </h1>
      <p class="last-updated">Last updated: December 12, 2024</p>

      <h2 class="section-title"><strong>General Terms</strong></h2>
      <p>
        By accessing and placing an order with DigitalSeal Studio, you confirm
        that you are in agreement with and bound by the terms of service
        contained in the Terms & Conditions outlined below. These terms apply to
        the entire website and any email or other type of communication between
        you and DigitalSeal Studio.
      </p>

      <p>
        Under no circumstances shall DigitalSeal Studio team be liable for any
        direct, indirect, special, incidental or consequential damages,
        including, but not limited to, loss of data or profit, arising out of
        the use, or the inability to use, the materials on this site, even if
        DigitalSeal Studio team or an authorized representative has been advised
        of the possibility of such damages.
      </p>

      <h2 class="section-title"><strong>License</strong></h2>
      <p>
        DigitalSeal Studio grants you a revocable, non-exclusive,
        non-transferable, limited license to download, install and use the
        website strictly in accordance with the terms of this Agreement.
      </p>

      <h2 class="section-title"><strong>Definitions and Key Terms</strong></h2>
      <p>
        To help explain things as clearly as possible in this Terms &
        Conditions, every time any of these terms are referenced, are strictly
        defined as:
      </p>
      <ul>
        <li>
          <strong>Cookie:</strong> small amount of data generated by a website
          and saved by your web browser. It is used to identify your browser,
          provide analytics, remember information about you.
        </li>
        <li>
          <strong>Company:</strong> when this policy mentions "Company," "we,"
          "us," or "our," it refers to DigitalSeal Studio that is responsible
          for your information under this Terms & Conditions.
        </li>
        <li>
          <strong>Service:</strong> refers to the seal creation platform and
          services provided by DigitalSeal Studio.
        </li>
        <li>
          <strong>Website:</strong> DigitalSeal Studio's site, which can be
          accessed via https://sealsdigital.com/
        </li>
        <li>
          <strong>You:</strong> a person or entity that is registered with
          DigitalSeal Studio to use the Services.
        </li>
      </ul>

      <h2 class="section-title"><strong>Restrictions</strong></h2>
      <p>You agree not to, and you will not permit others to:</p>
      <ul>
        <li>
          License, sell, rent, lease, assign, distribute, transmit, host,
          outsource, disclose or otherwise commercially exploit the website or
          make the platform available to any third party.
        </li>
        <li>
          Modify, make derivative works of, disassemble, decrypt, reverse
          compile or reverse engineer any part of the website.
        </li>
        <li>
          Remove, alter or obscure any proprietary notice of DigitalSeal Studio
          or its affiliates, partners, suppliers or the licensors of the
          website.
        </li>
      </ul>

      <h2 class="section-title"><strong>Contact Us</strong></h2>
      <p>
        For any questions about these Terms & Conditions, please contact us
        through our contact page.
      </p>
    </div>
  </LandingContainer>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'landing',
})
</script>

<style scoped>
.terms-conditions {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.policy-title {
  font-size: 2em;
  margin-bottom: 20px;
  text-align: center;
}

.last-updated {
  text-align: center;
  color: #666;
  margin-bottom: 30px;
}

.section-title {
  margin-top: 30px;
  margin-bottom: 15px;
  color: #333;
}

p {
  margin-bottom: 15px;
  line-height: 1.6;
}

ul {
  margin-bottom: 20px;
  padding-left: 20px;
}

li {
  margin-bottom: 8px;
}

.link {
  text-decoration: underline;
  color: #007bff;
}

.link:hover {
  color: #0056b3;
}
</style>
